/**
 * DO NOT EDIT THIS FILE
 * DO NOT EDIT THIS FILE
 * DO NOT EDIT THIS FILE
 * DO NOT EDIT THIS FILE
 * DO NOT EDIT THIS FILE
 *
 * For configuring Angular CLI with hot module reload
 * https://github.com/angular/angular-cli/wiki/stories-configure-hmr
 *
 */
import { NgModuleRef, ApplicationRef } from '@angular/core';
import { createNewHosts } from '@angularclass/hmr';

export const hmrBootstrap = (module: any, bootstrap: () => Promise<NgModuleRef<any>>) => {
  let ngModule: NgModuleRef<any>;
  module.hot.accept();
  bootstrap().then(mod => ngModule = mod);
  module.hot.dispose(() => {
    if (!ngModule) {
      console.log('[HMR] APPLICATION STATE UNSTABLE - Forcing browser reload.');
      window.location.reload();
    }
    const appRef: ApplicationRef = ngModule.injector.get(ApplicationRef);
    const elements = appRef.components.map(c => c.location.nativeElement);
    const makeVisible = createNewHosts(elements);
    ngModule.destroy();
    makeVisible();
  });
};
