// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

// This file only serves to set the `hmr` flag and extend the dev environment

import { environment as devEnvironment } from './environment.dev';

export const environment = {
  ...devEnvironment,
  hmr: true,
};
